# Generated by Django 6.0.3 on 2026-04-14 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_rating_per_user_per_project',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('project', 'user')},
        ),
    ]
