# Generated by Django 6.0.3 on 2026-04-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_rating_unique_rating_per_user_per_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
