# Generated by Django 6.0.4 on 2026-04-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_target_time_and_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
    ]
